# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
  branches:
    include:
      - "*"

pool:
  vmImage: 'ubuntu-latest'

container:
  image: sonicdev-microsoft.azurecr.io:443/sonic-slave-buster:latest

steps:
- script: |
    sudo apt-get install -qq -y \
      libhiredis-dev \
      libnl-3-dev \
      libnl-genl-3-dev \
      libnl-route-3-dev \
      libnl-nf-3-dev \
      swig3.0
  displayName: "Install Dependencies"
- script: |
    ./autogen.sh
    dpkg-buildpackage -us -uc -b
    cp ../*.deb .
  displayName: "Compile SONiC SWSS Common"
- publish: $(System.DefaultWorkingDirectory)/
  artifact: sonic-swss-common
